name = "project1"
uuid = "245c0858-0dd0-4a9e-aac7-6fef10f69a1c"
authors = ["jratkovec <justin.ratkovec@colorado.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
